FROM ubuntu:latest
MAINTAINER simran <simrankumari1344@gamil.com>
RUN apt-get update && apt-get install -y curl wget
RUN apt-get install python -y
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
